vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.tabstop = 2
vim.o.signcolumn = "yes"
vim.opt.shiftwidth = 2
vim.opt.clipboard = "unnamedplus"
vim.opt.swapfile = false
vim.g.mapleader = " "
vim.opt.winborder = "rounded"
vim.opt.colorcolumn = "100"
vim.opt.conceallevel = 2
vim.opt.hlsearch = false
vim.opt.foldcolumn = "1"
vim.opt.foldlevel = 99
vim.opt.foldlevelstart = 99
vim.opt.foldenable = true
vim.opt.termguicolors = true
