-- ts is so ass

require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.blinkcmp")
require("plugins.flash")
require("plugins.fzf-lua")
require("plugins.indent-blankline")
require("plugins.colors")
require("plugins.luasnip")
require("plugins.luau-lsp")
require("plugins.markdown-preview")
require("plugins.marksman")
require("plugins.mason")
require("plugins.mini-icons")
require("plugins.none-ls")
require("plugins.nvim-colorizer")
require("plugins.nvim-lspconfig")
require("plugins.nvim-web-icons")
require("plugins.obsidian")
require("plugins.oil")
require("plugins.render-markdown")
require("plugins.strudel")
require("plugins.ufo")
require("plugins.vim-tmux-navigator")
require("plugins.packmanager")
